import Config

# Configure your database
config :post_meet, PostMeet.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "post_meet_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :post_meet, PostMeetWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "cBRwRB/z3HOXO5maKcZsxAyHBM02pBmzVH5YcNj7XDtNMEyJEyIFq1vstQL+S1/1",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:post_meet, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:post_meet, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :post_meet, PostMeetWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/post_meet_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :post_meet, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Set default Recall.ai API key for development
config :post_meet, :recall_ai_api_key, System.get_env("RECALL_AI_API_KEY")

# Social Media API Configuration
config :post_meet,
  linkedin_client_id: System.get_env("LINKEDIN_CLIENT_ID"),
  linkedin_client_secret: System.get_env("LINKEDIN_CLIENT_SECRET"),
  linkedin_redirect_uri: System.get_env("LINKEDIN_REDIRECT_URI", "http://localhost:4000/auth/linkedin/callback"),
  facebook_app_id: System.get_env("FACEBOOK_APP_ID"),
  facebook_app_secret: System.get_env("FACEBOOK_APP_SECRET"),
  facebook_redirect_uri: System.get_env("FACEBOOK_REDIRECT_URI", "http://localhost:4000/auth/facebook/callback")
